---
- name: Setup nginx web server
  hosts: webservers
  become: true

  vars_files:
    - vars/default.yml

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: Configure nginx
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  - name: Ensure nginx is running and enabled on startup
    service:
      name: nginx
      state: started
      enabled: true

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

